version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'java-db'
    environment:
      - 'POSTGRES_DB=apiweb'
      - 'POSTGRES_PASSWORD=passwd'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    networks:
      - pg-network
    env_file:
      - .env
    volumes:
      - ./carga.sql:/docker-entrypoint-initdb.d/01-carga.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg-network
    env_file:
      - .env

networks:
  pg-network:
